# Generated by Django 5.1.7 on 2025-03-10 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_reading", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ielts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("so'z keritish", "so'z keritish"),
                    ("tf", "True/False"),
                    ("tanlov", "tanlov"),
                ],
                default="mcq",
                max_length=20,
                verbose_name="Savol turi",
            ),
        ),
    ]
