# Generated by Django 5.1.7 on 2025-03-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_reading", "0002_alter_ielts_user_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(
                blank=True,
                help_text="To'g'ri javob (ChatGPT tekshirish uchun)",
                max_length=40,
            ),
        ),
    ]
