# Generated by Django 5.1.7 on 2025-03-10 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_reading", "0003_alter_question_correct_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingtest",
            name="IELTS",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mock_reading.ielts",
            ),
        ),
    ]
