# Generated by Django 5.1.7 on 2025-03-10 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_reading", "0004_readingtest_ielts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mock_reading.task"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="reading_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mock_reading.readingtest",
            ),
        ),
    ]
