# Generated by Django 5.1.7 on 2025-03-10 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_reading", "0005_alter_question_task_alter_task_reading_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("so'z keritish", "so'z kiritish"),
                    ("tf", "True/False"),
                    ("tanlov", "tanlov"),
                ],
                default="mcq",
                max_length=20,
                verbose_name="Savol turi",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="mock_reading.task",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="variant_soni",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="nechta javob ni kiritish mumkin"
            ),
        ),
        migrations.AlterField(
            model_name="readingtest",
            name="IELTS",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_tests",
                to="mock_reading.ielts",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="reading_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="mock_reading.readingtest",
            ),
        ),
    ]
