# Generated by Django 5.1.7 on 2025-03-11 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mock_reading",
            "0006_alter_question_question_type_alter_question_task_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="user_answer",
            new_name="answer_text",
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="answer",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("so'z keritish", "so'z keritish"),
                    ("tf", "True/False"),
                    ("tanlov", "tanlov"),
                ],
                default="mcq",
                max_length=20,
                verbose_name="Savol turi",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="variant_soni",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="nechta javob ni keritish mumkun"
            ),
        ),
        migrations.AlterField(
            model_name="readingtest",
            name="IELTS",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mock_reading.ielts",
            ),
        ),
        migrations.RemoveField(
            model_name="answer",
            name="ai_feedback",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="exam_session",
        ),
        migrations.DeleteModel(
            name="ExamSession",
        ),
    ]
