# Generated by Django 5.1.7 on 2025-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_reading", "0008_alter_answer_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="question_text",
            new_name="task_text",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="question",
            name="correct_answer",
        ),
        migrations.RemoveField(
            model_name="question",
            name="variant_soni",
        ),
        migrations.AddField(
            model_name="question",
            name="True_False",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "yes"),
                    ("no", "no"),
                    ("True", "True"),
                    ("False", "False"),
                    ("Not given", "Not given"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="a",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="b",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="c",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_test_ansver",
            field=models.CharField(
                blank=True,
                choices=[("a", "a"), ("b", "b"), ("c", "c"), ("d", "d")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="d",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="enter_word",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="suzni kerililadi"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("so'z keritish", "so'z keritish"),
                    ("tf", "True/False"),
                    ("test", "test"),
                ],
                default="",
                max_length=20,
                verbose_name="Savol turi",
            ),
        ),
    ]
