# Generated by Django 5.1.7 on 2025-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_reading", "0009_rename_question_text_task_task_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ielts",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
