# Generated by Django 5.1.7 on 2025-04-09 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_reading", "0011_testresult"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="user",
        ),
        migrations.AddField(
            model_name="answer",
            name="pupil",
            field=models.ForeignKey(
                default=None,
                limit_choices_to={"role": "pupil"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answer",
            name="reading_test",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="mock_reading.readingtest",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="TestResult",
        ),
    ]
