# Generated by Django 5.1.7 on 2025-04-09 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_reading", "0012_remove_answer_updated_at_remove_answer_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="pupil",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "pupil"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
