# Generated by Django 5.1.7 on 2025-04-10 08:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_reading", "0013_alter_answer_pupil"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="PupilReadingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct_answers", models.IntegerField()),
                ("incorrect_answers", models.IntegerField()),
                ("score", models.FloatField()),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "pupil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reading_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_reading.readingtest",
                    ),
                ),
            ],
        ),
    ]
