# Generated by Django 5.1.7 on 2025-04-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_reading", "0014_alter_question_options_pupilreadingresult"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="correct_test_ansver",
            new_name="correct_test_answer",
        ),
        migrations.RemoveField(
            model_name="question",
            name="True_False",
        ),
        migrations.AddField(
            model_name="question",
            name="true_or_false",
            field=models.CharField(
                blank=True,
                choices=[
                    ("True", "True"),
                    ("False", "False"),
                    ("Not given", "Not given"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
