# Generated by Django 5.2 on 2025-04-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mock_reading', '0015_rename_correct_test_ansver_question_correct_test_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('allow_time', models.PositiveIntegerField(help_text='Ruxsat etilgan vaqt (daqiqa)')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ielts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writings', to='mock_reading.ielts')),
            ],
        ),
        migrations.CreateModel(
            name='WritingTaskFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='writing/task1/pdfs/')),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='writing/task1/images/')),
                ('exam_img', models.ImageField(blank=True, null=True, upload_to='writing/task1/images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_firsts', to='mock_writing.writing')),
            ],
        ),
        migrations.CreateModel(
            name='WritingTaskSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_seconds', to='mock_writing.writing')),
            ],
        ),
    ]
