# Generated by Django 5.2 on 2025-04-16 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_writing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField(choices=[(1, 'Task 1'), (2, 'Task 2')])),
                ('answer_text', models.TextField()),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('checked_by_ai', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_writing.writing')),
            ],
        ),
    ]
